backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

django_articles/urls.py
from django.urls import path

from django_articles.views import (
    AuthorIndexView,
    AuthorDetailView,
    ArticleIndexView,
    ArticleDetailView,
    TagIndexView,
    TagRelationsIndexView
)


app_name = 'django_articles'

urlpatterns = [
    path('authors/', AuthorIndexView.as_view(), name='author-index'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='author-detail'),
    path('articles/', ArticleIndexView.as_view(), name='article-index'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
    path('tags/', TagIndexView.as_view(), name='tag-index'),
    path('tags/<int:pk>/', TagRelationsIndexView.as_view(), name='tag-relations-index')
]

django_articles/views.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.views import generic

from .models import Article, Tag


class AuthorIndexView(generic.ListView):
    template_name = 'django_articles/author_index.html'
    context_object_name = 'authors_list'

    def get_queryset(self):
        """
        Returns a query set that includes authors of published articles.
        """
        return User.objects.all().order_by('username')
    

class AuthorDetailView(generic.DetailView):
    model = User
    template_name = 'django_articles/author_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.get_object()
        articles = author.articles.filter(
            pub_date__lte=timezone.now()
        ).exclude(
            title=''
        ).exclude(
            tags__isnull=True
        ).exclude(
            content=''
        )
        context['articles'] = articles
        return context


class ArticleIndexView(generic.ListView):
    template_name = 'django_articles/article_index.html'
    context_object_name = 'published_articles_list'

    def get_queryset(self):
        """
        Returns a query set that includes articles whose pub_date is present or past, and excludes articles with empty fields.
        """
        return Article.objects.filter(
            pub_date__lte=timezone.now()
        ).exclude(
            title=''
        ).exclude(
            tags__isnull=True
        ).exclude(
            content=''
        )
    

class ArticleDetailView(generic.DetailView):
    template_name = 'django_articles/article_detail.html'

    def get_queryset(self):
        """
        Returns article whose primary key is provided in the request.
        """
        search_request = self.request.resolver_match.kwargs.get('pk')
        return Article.objects.filter(
            pk=search_request,
            pub_date__lte=timezone.now()
        ).exclude(
            title=''
        ).exclude(
            tags__isnull=True
        ).exclude(
            content=''
        )


class TagIndexView(generic.ListView):
    template_name = 'django_articles/tag_index.html'
    context_object_name = 'available_tags_list'

    def get_queryset(self):
        """
        Returns query set of all tags in database.
        """
        return Tag.objects.all()
    

class TagRelationsIndexView(generic.ListView):
    template_name = 'django_articles/tag_relations_index.html'
    context_object_name = 'tag_relations_list'

    def get_queryset(self):
        """
        Returns a query set of articles whose tags contain the tag with primary key provided in the request, and excludes articles with empty fields.
        """
        search_request = self.request.resolver_match.kwargs.get('pk')
        return Article.objects.filter(
            tags__pk=search_request,
            pub_date__lte=timezone.now()
        ).exclude(
            title=''
        ).exclude(
            tags__isnull=True
        ).exclude(
            content=''
        )

django_articles/templates/django_articles/article_detail.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Article detail page</title>
    </head>
    <body>
        <h1>Title: {{ article.title }}</h1>
        <h2>Author: <a href="{% url 'django_articles:author-detail' article.author.id %}">{{ article.author }}</a></h2>
        <h3>Tags:</h3>
        <ul>
            {% for tag in article.get_related_tags %}
            <li><a href="{% url 'django_articles:tag-relations-index' tag.id %}">{{ tag.name }}</a></li>
            {% endfor %}
        </ul>
        <h4>{{ article.pub_date }}</h4>
        <p>{{ article.content }}</p>
    </body>
</html>

django_articles/templates/django_articles/article_index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Article index page</title>
    </head>
    <body>
        {% if published_articles_list %}
            <ul>
                {% for article in published_articles_list %}
                <li><a href="{% url 'django_articles:article-detail' article.id %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No articles are available.</p>
        {% endif %}
    </body>
</html>

django_articles/templates/django_articles/articles_detail.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Articles detail</title>
    </head>
    <body>
        <h1>{{ article.title }}</h1>
        <h2>{{ article.tags_as_str }}</h2>
        <h3>{{ article.pub_date }}</h3>
        <p>{{ article.content }}</p>
    </body>
</html>

django_articles/templates/django_articles/articles_index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Articles index</title>
    </head>
    <body>
        {% if published_articles_list %}
            <ul>
                {% for article in published_articles_list %}
                <li><a href="{% url 'django_articles:articles_detail' article.id %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No articles are available.</p>
        {% endif %}
    </body>
</html>

django_articles/templates/django_articles/author_detail.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Author detail page</title>
    </head>
    <body>
        <h1>Author info:</h1>
        <p>Name: {{ user.username }}</p>
        {% if user.email %}
            <p>E-mail: {{ user.email }}</p>
        {% endif %}
        {% if articles %}
            <h2>Published articles:</h2>
            <ul>
                {% for article in articles %}
                <li><a href="{% url 'django_articles:article-detail' article.id %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <h2>Has not published any articles yet.</h2>
        {% endif %}
    </body>
</html>

django_articles/templates/django_articles/author_index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Author index page</title>
    </head>
    <body>
        {% if authors_list %}
            <ul>
                {% for author in authors_list %}
                <li><a href="{% url 'django_articles:author-detail' author.id %}">{{ author.username }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No authors are available.</p>
        {% endif %}
    </body>
</html>

django_articles/templates/django_articles/tag_index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Tags index page</title>
    </head>
    <body>
        {% if available_tags_list %}
            <ul>
                {% for tag in available_tags_list %}
                <li><a href="{% url 'django_articles:tag-relations-index' tag.id %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No tags are available.</p>
        {% endif %}
    </body>
</html>

django_articles/templates/django_articles/tag_relations_index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Tags relations index page</title>
    </head>
    <body>
        {% if tag_relations_list %}
            <ul>
                {% for article in tag_relations_list %}
                <li><a href="{% url 'django_articles:article-detail' article.id %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No articles are available.</p>
        {% endif %}
    </body>
</html>

django_articles/templates/django_articles/tags_index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Tags index</title>
    </head>
    <body>
        {% if available_tags_list %}
            <ul>
                {% for tag in available_tags_list %}
                <li><a href="{% url 'django_articles:tags_relations_index' tag.id %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No tags are available.</p>
        {% endif %}
    </body>
</html>

django_articles/templates/django_articles/tags_relations_index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Tags relations index</title>
    </head>
    <body>
        {% if tags_relations_list %}
            <ul>
                {% for article in tags_relations_list %}
                <li><a href="{% url 'django_articles:articles_detail' article.id %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No articles are available.</p>
        {% endif %}
    </body>
</html>