backend/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import (
    ArticleViewSet,
    TagViewSet,
    AuthorViewSet,
)

router = DefaultRouter()
router.register(r'authors', AuthorViewSet)
router.register(r'articles', ArticleViewSet)
router.register(r'tags', TagViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

backend/library/urls.py
from django.urls import path, re_path
from django.views import generic

from . import views as library_views


app_name = 'library'

urlpatterns = [
    path(
        '', generic.TemplateView.as_view(
            template_name='library/index.html'
        ), name='index'
    ),
    path(
        'articles/', library_views.ArticleListView.as_view(), name='article-list'
    ),
    re_path(
        r'^(?:article-(?P<slug>[0-9-a-z]+))/$', library_views.ArticleDetailView.as_view(), name='article-detail'
    ),
    path(
        'authors/', library_views.AuthorListView.as_view(), name='author-list'
    ),
    re_path(
        r'^(?:author-(?P<slug>[0-9-a-z]+))/$', library_views.AuthorDetailView.as_view(), name='author-detail'
    ),
    path(
        'tags/', library_views.TagListView.as_view(), name='tag-list'
    ),
    re_path(
        r'^(?:tag-(?P<slug>[0-9-a-z]+))/$', library_views.TagDetailView.as_view(), name='tag-detail'
    ),
    path(
        'register/', library_views.UserRegisterView.as_view(), name='user-register'
    ),
    path(
        'login/', library_views.UserLoginView.as_view(), name='user-login'
    ),
    path(
        'logout/', library_views.UserLogoutView.as_view(), name='user-logout'
    ),
]

django_articles/urls.py
from django.urls import path

from django_articles.views import (
    AuthorIndexView,
    AuthorDetailView,
    ArticleIndexView,
    ArticleDetailView,
    TagIndexView,
    TagRelationsIndexView
)


app_name = 'django_articles'

urlpatterns = [
    path('authors/', AuthorIndexView.as_view(), name='author-index'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='author-detail'),
    path('articles/', ArticleIndexView.as_view(), name='article-index'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
    path('tags/', TagIndexView.as_view(), name='tag-index'),
    path('tags/<int:pk>/', TagRelationsIndexView.as_view(), name='tag-relations-index')
]

backend/library/models.py
from django.contrib import admin
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

from .managers import CustomArticleManager, CustomAuthorManager


class Article(models.Model):
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True)
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag')
    pub_date = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    objects = models.Manager()
    verified_objects = CustomArticleManager()

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'articles'

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    @admin.display(description='tags')
    def tags_as_str(self) -> str:
        """
        Returns names of all tags related with an article as a single string.
        """
        return ', '.join(tag.name for tag in self.tags.all())
    

class Author(AbstractBaseUser, PermissionsMixin):
    DEFAULT_AVATAR = 'static/library/author/default/default_avatar.png'

    def create_avatar_path(instance, filename):
        """
        Creates a path where Author avatar will be uploaded.
        """
        return f'static/library/author/{instance.user_name}/{filename}'

    user_name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True)
    email = models.EmailField(max_length=250, unique=True)
    avatar = models.ImageField(default=DEFAULT_AVATAR, upload_to=create_avatar_path)
    joined = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = CustomAuthorManager()
    
    USERNAME_FIELD = 'user_name'
    REQUIRED_FIELDS = ['email']

    class Meta:
        ordering = ['user_name']

    def __str__(self):
        return self.user_name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user_name)
        super().save(*args, **kwargs)


class Tag(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

backend/library/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password

from .models import Author


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm password')
    
    class Meta:
        model = Author
        fields = [
            'user_name', 'email', 'avatar', 'password'
        ]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        validate_password(password)
        password2 = cleaned_data.get('password2')
        if password and password2 and password != password2:
            self.add_error('password2', 'Passwords dont match')
        return cleaned_data

backend/api/views.py
from rest_framework import mixins
from rest_framework import permissions
from rest_framework import viewsets

from .permissions import (
    ArticleIsOwnerOrReadOnly,
    AuthorIsSelfOrReadOnly,
    IsStaffOrReadOnly,
    IsAnonymousOrNotAllowed,
)
from .serializers import (
    AuthorSerializer,
    ArticleSerializer,
    TagSerializer,
)
from library.models import Article, Author, Tag


class ArticleViewSet(viewsets.ModelViewSet):
    """
    Allows anyone to display published articles and
    to create a new article by logged in User.
    
    Uses custom permission `ArticleIsOwnerOrReadOnly` that allows only
    author of an article to edit it.
    """
    queryset = Article.verified_objects.all()
    serializer_class = ArticleSerializer
    lookup_field = 'slug'
    permission_classes = [
        permissions.IsAuthenticatedOrReadOnly, ArticleIsOwnerOrReadOnly
    ]


class AuthorViewSet(viewsets.ModelViewSet):
    """
    Allows anyone to display users and
    to create a new account by anonymous visitors.

    Uses custom permission `IsAnonymousOrNotAllowed` that allows only
    not logged in user to create an account.

    Uses custom permission `AuthorIsSelfOrReadOnly` that allows only
    a user to manage his personal data.
    """
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    lookup_field = 'slug'
    permission_classes = [IsAnonymousOrNotAllowed, AuthorIsSelfOrReadOnly]


class TagViewSet(viewsets.ModelViewSet):
    """
    Allows anyone to display tags and articles related to them.
    
    Uses custom permission `IsStaffOrReadOnly` that allows only
    an staff user to manage tags.
    """
    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    lookup_field = 'slug'
    permission_classes = [IsStaffOrReadOnly]

backend/library/views.py
from django.contrib.auth import views as auth_views
from django.http import Http404
from django.views import generic
from django.urls import reverse_lazy

from .forms import UserRegisterForm
from .mixins import RedirectAuthenticatedUserMixin, RedirectUnAuthenticatedUserMixin
from .models import Article, Author, Tag


class ArticleListView(generic.ListView):
    template_name = 'library/article_list.html'
    context_object_name = 'published_articles_list'

    def get_queryset(self):
        """
        Returns a query set that includes verified articles
        whose pub_date is present or past.
        """
        return Article.verified_objects.all()
    

class ArticleDetailView(generic.DetailView):
    template_name = 'library/article_detail.html'

    def get_object(self):
        """
        Returns verified article whose slug was provided in the request.
        If it not exists, raises 404.
        """
        try:
            return Article.verified_objects.get(slug=self.kwargs['slug'])
        except Article.DoesNotExist:
            raise Http404


class AuthorListView(generic.ListView):
    emplate_name = 'library/author_list.html'
    context_object_name = 'authors_list'

    def get_queryset(self):
        """
        Returns a query set that includes authors of published articles.
        """
        return Author.objects.all()


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'library/author_detail.html'

    def get_context_data(self, **kwargs):
        """
        Returns a queryset of articles related with an author,
        excludes defective articles.
        """
        context = super().get_context_data(**kwargs)
        author_obj = self.get_object()
        articles = Article.verified_objects.filter(author__slug=author_obj.slug)
        context['articles'] = articles
        return context


class TagListView(generic.ListView):
    template_name = 'library/tag_list.html'
    context_object_name = 'available_tags_list'

    def get_queryset(self):
        """
        Returns query set of all tags in database.
        """
        return Tag.objects.all()
    

class TagDetailView(generic.DetailView):
    model = Tag
    template_name = 'library/tag_detail.html'

    def get_context_data(self, **kwargs):
        """
        Returns a query set of verified articles whose
        tags contain the tag with primary key provided in the request.
        """
        context = super().get_context_data(**kwargs)
        tag_obj = self.get_object()
        articles = Article.verified_objects.filter(tags__slug=tag_obj.slug)
        context['articles'] = articles
        return context
    

class UserRegisterView(RedirectAuthenticatedUserMixin, generic.FormView):
    form_class = UserRegisterForm
    template_name = 'library/user_register.html'
    success_url = reverse_lazy('library:user-login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        return super().form_valid(form)


class UserLoginView(RedirectAuthenticatedUserMixin, auth_views.LoginView):
    template_name = 'library/user_login.html'
    next_page = 'library:index'


class UserLogoutView(RedirectUnAuthenticatedUserMixin, auth_views.LogoutView):
    template_name = 'library/user_logout.html'

skills_backend/library/api/views.py
from django.contrib.auth.models import User
from rest_framework import mixins
from rest_framework import permissions
from rest_framework import viewsets

from library.api.permissions import IsAnonymousOrNotAllowed ,IsOwnerOrReadOnly
from library.api.serializers import ArticleSerializer, TagSerializer, UserSerializer
from library.models import Article, Tag


class ArticleViewSet(viewsets.ModelViewSet):
    """
    Allows anyone to display published articles and to create a new article by logged in User.
    
    Uses custom permission `IsOwnerOrReadOnly` that ensures only author of article can edit it.
    """
    queryset = Article.verified_objects.all()
    serializer_class = ArticleSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        """
        Assings User who create article as author of it.
        """
        serializer.save(author=self.request.user)


class TagViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Allows anyone to display tags and articles related to them.
    """
    queryset = Tag.objects.all()
    serializer_class = TagSerializer


class UserViewSet(mixins.ListModelMixin, mixins.RetrieveModelMixin, mixins.CreateModelMixin, viewsets.GenericViewSet):
    """
    Allows anyone to display users and create a new account by anonymous visitors.

    Uses custom permission `IsAnonOrNotAllowed` that ensures only not loggen in user can create account.
    """
    queryset = User.objects.all().order_by('username')
    serializer_class = UserSerializer
    permission_classes = [IsAnonymousOrNotAllowed]

backend/templates/library/article_detail.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Article</title>
    </head>
    <body>
        <div>
            <a href="{% url 'library:index' %}"><button>Home page</button></a>
            <a href="{% url 'library:article-list' %}"><button>Articles list</button></a>
        </div>
        <div>
            <h2>{{ article.title }}</h2>
            <p>Author: <a href="{% url 'library:author-detail' article.author.slug %}">{{ article.author }}</a></p>
            <p>Tags:</p>
            <ul>
                {% for tag in article.tags.all %}
                <li><a href="{% url 'library:tag-detail' tag.slug %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
            <p>Published: {{ article.pub_date }}</p>
            <p>{{ article.content }}</p>
        </div>
    </body>
</html>

backend/templates/library/article_list.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Articles</title>
    </head>
    <body>
        <div>
            <a href="{% url 'library:index' %}"><button>Home page</button></a>
        </div>
        <div>
            {% if published_articles_list %}
            <h3>Published articles:</h3>
            <ul>
                {% for article in published_articles_list %}
                <li><a href="{% url 'library:article-detail' article.slug %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <h3>No articles are available.</h3>
            {% endif %}
        </div>
    </body>
</html>

backend/templates/library/author_detail.html
<!DOCTYPE html>
<html lang="en-US">
{% load static %}
    <head>
        <meta charset="utf-8" />
        <title>Skills | Author</title>
    </head>
    <body>
        <div>
            <a href="{% url 'library:index' %}"><button>Home page</button></a>
            <a href="{% url 'library:author-list' %}"><button>Authors list</button></a>
        </div>
        <div>
            <h2>{{ author.user_name }}</h2>
            <img src="{{ author.avatar.url }}" style="width:200px;height:200px;">
            <p>{{ author.email }}</p>
            <p>Joined: {{ author.joined }}</p>
            {% if articles %}
            <h3>Published articles:</h3>
            <ul>
                {% for article in articles %}
                <li><a href="{% url 'library:article-detail' article.slug %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p3>Has not published any articles yet.</h3>
            {% endif %}
        </div>
    </body>
</html>

backend/templates/library/author_list.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Authors</title>
    </head>
    <body>
        <div>
            <a href="{% url 'library:index' %}"><button>Home page</button></a>
        </div>
        <div>
            {% if authors_list %}
            <ul>
                {% for author in authors_list %}
                <li><a href="{% url 'library:author-detail' author.slug %}">{{ author.user_name }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <h3>No authors are available.</h3>
            {% endif %}
        </div>
    </body>
</html>

backend/templates/library/index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Home</title>
    </head>
    <body>
        <div>
        {% if request.user.is_authenticated %}
            <form method="post" action="{% url 'library:user-logout' %}">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
        {% else %}
            <a href="{% url 'library:user-register' %}"><button>Register</button></a>
            <a href="{% url 'library:user-login' %}"><button>Login</button></a>
        {% endif %}
        </div>
        <div>
            <ul>
                <li><a href="{% url 'library:author-list' %}">Authors</a></li>
                <li><a href="{% url 'library:article-list' %}">Articles</a></li>
                <li><a href="{% url 'library:tag-list' %}">Tags</a></li>
            </ul>
        </div>
    </body>
</html>

backend/templates/library/tag_detail.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Tag</title>
    </head>
    <body>
        <div>
            <a href="{% url 'library:index' %}"><button>Home page</button></a>
            <a href="{% url 'library:tag-list' %}"><button>Tags list</button></a>
        </div>
        <div>
            <h2>{{ tag.name }}</h2>
            {% if articles %}
            <h3>Published articles:</h3>
            <ul>
                {% for article in articles %}
                <li><a href="{% url 'library:article-detail' article.slug %}">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <h3>No articles are available.</h3>
            {% endif %}
        </div>
    </body>
</html>

backend/templates/library/tag_list.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Tags</title>
    </head>
    <body>
        <div>
            <a href="{% url 'library:index' %}"><button>Home page</button></a>
        </div>
        <div>
            {% if available_tags_list %}
            <ul>
                {% for tag in available_tags_list %}
                <li><a href="{% url 'library:tag-detail' tag.slug %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <h3>No tags are available.</h3>
            {% endif %}
        </div>
    </body>
</html>

backend/templates/library/user_login.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Login</title>
    </head>
    <body>
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Login">
            </form>
        </div>
    </body>
</html>

backend/templates/library/user_logout.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Logout</title>
    </head>
    <body>
        <div>
            <a href="{% url 'library:user-login' %}">Login again?</a>
        </div>
    </body>
</html>

backend/templates/library/user_register.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Skills | Register</title>
    </head>
    <body>
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Register">
            </form>
        </div>
    </body>
</html>